apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "multi-model.fullname" . }}-config
  labels:
    {{- include "multi-model.labels" . | nindent 4 }}
data:
  config.yaml: |
    port: {{ .Values.config.port }}
    model: "{{ .Values.config.model }}"
    served-model-name:
    {{- toYaml .Values.config.servedModelName | nindent 4 }}
    max-loras: {{ .Values.config.maxLoras }}
    max-cpu-loras: {{ .Values.config.maxCpuLoras }}
    max-num-seqs: {{ .Values.config.maxNumSeqs }}
    max-waiting-queue-length: {{ .Values.config.maxWaitingQueueLength }}
    max-model-len: {{ .Values.config.maxModelLen }}
    {{- if .Values.config.loraModules }}
    lora-modules:
    {{- toYaml .Values.config.loraModules | nindent 4 }}
    {{- else }}
    lora-modules: []
    {{- end }}
    mode: "{{ .Values.config.mode }}"
    {{- with .Values.config.latencyCalculator }}
    latency-calculator: "{{ . }}"
    {{- end }}
    time-to-first-token: "{{ .Values.config.timeToFirstToken }}ms"
    {{- with .Values.config.timeToFirstTokenStdDev }}
    time-to-first-token-std-dev: "{{ . }}ms"
    {{- end }}
    inter-token-latency: "{{ .Values.config.interTokenLatency }}ms"
    {{- with .Values.config.interTokenLatencyStdDev }}
    inter-token-latency-std-dev: "{{ . }}ms"
    {{- end }}
    kv-cache-transfer-latency: "{{ .Values.config.kvCacheTransferLatency }}ms"
    {{- with .Values.config.kvCacheTransferLatencyStdDev }}
    kv-cache-transfer-latency-std-dev: "{{ . }}ms"
    {{- end }}
    {{- with .Values.config.prefillOverhead }}
    prefill-overhead: "{{ . }}"
    {{- end }}
    {{- with .Values.config.prefillTimePerToken }}
    prefill-time-per-token: "{{ . }}"
    {{- end }}
    {{- with .Values.config.prefillTimeStdDev }}
    prefill-time-std-dev: "{{ . }}"
    {{- end }}
    {{- with .Values.config.kvCacheTransferTimePerToken }}
    kv-cache-transfer-time-per-token: "{{ . }}"
    {{- end }}
    {{- with .Values.config.kvCacheTransferTimeStdDev }}
    kv-cache-transfer-time-std-dev: "{{ . }}"
    {{- end }}
    {{- with .Values.config.timeFactorUnderLoad }}
    time-factor-under-load: {{ . }}
    {{- end }}
    enable-kvcache: {{ .Values.config.enableKvcache }}
    {{- with .Values.config.kvCacheSize }}
    kv-cache-size: {{ . }}
    {{- end }}
    {{- with .Values.config.globalCacheHitThreshold }}
    global-cache-hit-threshold: {{ . }}
    {{- end }}
    {{- with .Values.config.blockSize }}
    block-size: {{ . }}
    {{- end }}
    seed: {{ int .Values.config.seed }}
    render-url: "http://localhost:{{ .Values.vllmRender.port }}"
